name: ci

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: temurin:1.17
          apps: scala-cli
      - name: Install NGINX Unit
        run: |
          curl -sL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
          echo "deb https://packages.nginx.org/unit/ubuntu/ focal unit" | sudo tee -a /etc/apt/sources.list.d/unit.list
          echo "deb-src https://packages.nginx.org/unit/ubuntu/ focal unit" | sudo tee -a /etc/apt/sources.list.d/unit.list
          sudo apt-get update
          unit_version="1.26*"
          sudo apt-get install -y libuv1-dev unit=$unit_version unit-dev=$unit_version
      - name: Test
        run: scala-cli test snunit-cli
      - name: Create binary
        run: scala-cli package snunit-cli -o snunit
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: snunit
